-- Story 07-01: server-managed personal API keys.
-- Raw bearer tokens are generated by the application and are never persisted.

create table public.api_keys (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null check (
    name = btrim(name)
    and char_length(name) between 1 and 120
  ),
  key_prefix text not null unique check (
    key_prefix ~ '^[A-Za-z0-9_-]{12}$'
  ),
  secret_digest text not null check (
    secret_digest ~ '^[0-9a-f]{64}$'
  ),
  last_used_at timestamptz,
  expires_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  check (expires_at is null or expires_at > created_at)
);

create index api_keys_user_created_idx
on public.api_keys (user_id, created_at desc);

create index api_keys_active_prefix_idx
on public.api_keys (key_prefix)
where revoked_at is null;

alter table public.api_keys enable row level security;

revoke all on table public.api_keys from public, anon, authenticated;
grant select, insert, update on table public.api_keys to service_role;
